### ISSUE TITLE
Proposed feature: persistent access to an entry

### ISSUE THREAD

**Issue by noopole** [WICG/entries-api#10]
Should it be possible to retain et restore entries (selected by the user), so that a web application could get a persistent access to a file or a directory on the user files system.

I was possile with Chrome App [api](https://developer.chrome.com/apps/fileSystem#method-restoreEntry) for example. 

The privacy aspect could be processed like for the camera / microphone access, with the possibility to revoke permissions at any moment (like from the permissions list in Chrome's adresse bar).

(I know this may not be the right place to post but I don't know a better one :)

**Comment by inexorabletash** [comment]
See also: https://github.com/w3c/IndexedDB/issues/56

**Comment by inexorabletash** [comment]
We're pursuing this over at https://github.com/WICG/writable-files/blob/master/EXPLAINER.md now - unlikely to introduce changes here.
