### ISSUE TITLE
Link to WebIDL TypeError or TypeMismatchError

### ISSUE THREAD

**Issue by tobie** [WICG/entries-api#14]
Added the missing [TypeMismatchError](https://heycam.github.io/webidl/#typemismatcherror) in WebIDL in https://github.com/heycam/webidl/commit/c50ffc45f6e8c19262aed531bbe6b047101c3b06.

Recommendation is to switch to TypeError if that's Web compatible, though. :)

**Comment by inexorabletash** [comment]
Thanks. Dropped the local definition of `TypeMismatchError`, left the note about switching to `TypeError` if web compatible.
