### ISSUE TITLE
webkitRelativePath should be relative to which directory?

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/entries-api#16]
According to the spec as written "the webkitRelativePath property of each File is set to a relative path from the selected directory to the file.". However that is not what is implemented in chrome. In chrome (apparently [intentionally](https://bugs.chromium.org/p/chromium/issues/detail?id=124187)) webkitRelativePath is relative to the smallest common ancestor of all selected files, regardless of if that was actually the directory selected.

**Comment by inexorabletash** [comment]
Thanks - I'll update.

**Comment by inexorabletash** [comment]
Other implementers may want to push back on that and consider it a Blink bug, but I'll default to describing the Blink behavior pending further feedback.

**Comment by inexorabletash** [comment]
Added spec prose, an example, and test. Thanks!
