### ISSUE TITLE
//foo is not a relative or absolute path

### ISSUE THREAD

**Issue by inexorabletash** [WICG/entries-api#19]
cc: @cdumez

Per https://github.com/w3c/web-platform-tests/issues/7647 the current definition of absolute path and relative path preclude `//foo`; a relative path can't start with `/` and an absolute path is `/` followed by a relative path.

Chrome treats `//foo` the same as `/foo` just as it treats `a//b` the same as `a/b` so we can fix by updating the definition of absolute path to:

> An absolute path is a string consisting of '/' (U+002F SOLIDUS) followed by zero or more path segments joined by '/' (U+002F SOLIDUS).

**Comment by cdumez** [comment]
I am OK with updating the spec. When this is done, I'll work on updating WebKit accordingly.
